### ISSUE TITLE
Rewrite compare method

### ISSUE THREAD

**Issue by dorienmc** [MinThaMie/graph_isomorphism#23]
Currently uses the Counter class from 'collections'. 
But we are not allowed to import stuff.

! Do not use sets, there might un-unique elements.

! Do not use List.sort() it changes the arguments, use sorted() if needed.
In that case, also make a `<` method for Vertex objects (or add to option for a lambda or something)

**Comment by MinThaMie** [comment]
#26 includes this new compare. Could use some improvements probably
