### ISSUE TITLE
Add pre-processing steps

### ISSUE THREAD

**Issue by MartijnSlot** [MinThaMie/graph_isomorphism#38]
Until now we've got:

[x] Remove loners
[x] Check for equal vertices
[] Check for cycularity (?)
[] Possible favorable cut conditions to split up graphs (?) Maybe this isn't part of preprocessing.

is linked to #4 Algorithm per type of graph

**Comment by erikhuizinga** [comment]
Ik denk wel dat 'favorable cut conditions' onderdeel zijn van preprocessing, maar ook weer niet:

Als je, voordat je begint met een algoritme, detecteert dat een graaf slimmer aangepakt kan worden dan met simpelweg branchen, dan bepaal je dus dat je een ander algoritme nodig hebt. Misschien moet je de graaf wel enigszins snoeien of vervormen. Dat is preprocessing.

Echter, als je halverwege het algoritme vindt dat een bepaalde truuk nodig is, dan moet je op dat moment ook een vorm van 'pre'processing kunnen doen en verdergaan met een slimmer algoritme (al dan niet voor een subgraaf).

Dus ik stel me voor dat het voorbewerkingsalgoritme een of twee graafobjecten als input heeft en dat de te verwerken graaf (bijv. disjoint union, module, component, ...) en het bijbehorende algoritme (bijv. fast colour refinement) worden teruggegeven. Daarmee kan de hoofdloop de graaf verder verwerken.
