### ISSUE TITLE
Algoritme per type Graph?

### ISSUE THREAD

**Issue by ClaudiaReuvers** [MinThaMie/graph_isomorphism#4]
Uitzoeken of het nut heeft om een ander algoritme toe te passen voor verschillende types Graphs

**Comment by MinThaMie** [comment]
Ik heb gevonden dat er voor veel verschillende structuren lineaire oplossingen te vinden zijn voor isomorfisme.
[planar-graph-iso-hopcroft.pdf](https://github.com/MinThaMie/graph_isomorphism/files/1833419/planar-graph-iso-hopcroft.pdf)

**Comment by MartijnSlot** [comment]
https://stackoverflow.com/questions/20556802/given-a-graph-to-detect-if-it-is-a-tree-or-not-in-directed-and-undirected-graphs

**Comment by MartijnSlot** [comment]
GI Algorithm comparison

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.98.2640&rep=rep1&type=pdf
