### ISSUE TITLE
Fast_color_refinement na splitten: moet je maar 1 of alles - 1 partities toevoegen aan de queue

### ISSUE THREAD

**Issue by ClaudiaReuvers** [MinThaMie/graph_isomorphism#47]
Op moment dat je een partitie splitst:
1) Kan het dan in meer dan 2 partities splitsen?
2) En zo ja, moet je dan slechts 1 partitie toevoegen aan de queue of alle nieuwe partities min de grootste?

**Comment by MinThaMie** [comment]
Antwoord van Utz, dus je kunt splitten in meer en dan mogen die bijna allemaal aan de queue worden toegevoegd
